version: "3"
services:
  nicfit-alpine-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: nicfit/alpine-base:${TAG}

  nicfit-alpine-python:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        TAG: ${TAG}
    image: nicfit/alpine-python:${TAG}

  nicfit-alpine-java:
    build:
      context: .
      dockerfile: Dockerfile.java
      args:
        TAG: ${TAG}
    image: nicfit/alpine-java:${TAG}

  nicfit-alpine-devel:
    build:
      context: .
      dockerfile: Dockerfile.devel
      args:
        TAG: ${TAG}
    image: nicfit/alpine-devel:${TAG}

  nicfit-alpine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${TAG}
    image: nicfit/alpine:${TAG}
