FROM alpine:latest
MAINTAINER <nicfit@gmail.com>

ENV LANG en_US.UTF-8

#RUN locale-gen

RUN apk update &&\
    apk upgrade &&\
    apk add --no-cache bash \
                       ca-certificates \
                       procps \
                       sudo \
                       vim

ONBUILD RUN apk update &&\
            apk upgrade
