version: "3"

services:
  nicfit-archlinux-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: nicfit/archlinux-base:${TAG}

  nicfit-archlinux-python:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        TAG: ${TAG}
    image: nicfit/archlinux-python:${TAG}

  nicfit-archlinux-java:
    build:
      context: .
      dockerfile: Dockerfile.java
      args:
        TAG: ${TAG}
    image: nicfit/archlinux-java:${TAG}

  nicfit-archlinux-devel:
    build:
      context: .
      dockerfile: Dockerfile.devel
      args:
        TAG: ${TAG}
    image: nicfit/archlinux-devel:${TAG}

  nicfit-archlinux:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: ${TAG}
    image: nicfit/archlinux:${TAG}
