FROM archlinux/base
MAINTAINER <nicfit@gmail.com>

ENV LANG en_US.UTF-8

RUN locale-gen

COPY bootstrap/mirrorlist /etc/pacman.d/

ONBUILD RUN pacman-key --init && \
            pacman-key --populate archlinux && \
            pacman -Syu --noconfirm && \
            pacman -S --noconfirm --needed ca-certificates sudo vim
