ARG VERSION=local
FROM nicfit/archlinux-base:${VERSION}
MAINTAINER <nicfit@gmail.com>

RUN pacman -Syu --noconfirm --needed \
                base-devel git \
                python python-pip \
                jdk-openjdk

